apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-aws-ram-share
spec:
  package: ghcr.io/hops-ops/configuration-aws-ram-share:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}

---

# skipDependencyResolution false would name this hops-ops-configuration-aws-ram-sharerender
# so we need to match that format to avoid issues with the package name
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-configuration-aws-ram-sharerender
spec:
  package: ghcr.io/hops-ops/configuration-aws-ram-share_render:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}
