name: on-push-main

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.github/workflows/on-version-tagged.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'functions/**'
      - 'tests/**'
      - 'upbound.yaml'

permissions:
  id-token: write
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.7.0
    with:
      examples: |
        [
          { "example": "examples/ramshares/minimal.yaml" },
          { "example": "examples/ramshares/minimal.yaml", "observed_resources": "examples/test/mocks/observed-resources/minimal-ready/" },
          { "example": "examples/ramshares/ipam-pools.yaml" },
          { "example": "examples/ramshares/transit-gateway.yaml" },
          { "example": "examples/ramshares/private-ca.yaml" }
        ]
      api_path: apis/ramshares
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.7.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.7.0
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      timeout-minutes: 33

  version-and-tag:
    name: Version and Tag
    needs: 
      - validate 
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.20.2
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
      yqPatches: |
        patches:
          - filePath: .gitops/deploy/values.yaml
            selector: .version
            valuePrefix: "v"
          - filePath: .gitops/deploy/Chart.yaml
            selector: .version
            valuePrefix: ""
