name: on-pr

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
    paths:
      - '.github/workflows/on-pr.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.6.0
    with:
      examples: |
        [
          { "example": "examples/ramshares/minimal.yaml" },
          { "example": "examples/ramshares/minimal.yaml", "observed_resources": "examples/test/mocks/observed-resources/minimal-ready/" },
          { "example": "examples/ramshares/ipam-pools.yaml" },
          { "example": "examples/ramshares/transit-gateway.yaml" },
          { "example": "examples/ramshares/private-ca.yaml" }
        ]
      api_path: apis/ramshares
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.6.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.6.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true
      timeout-minutes: 33

  publish:
    needs: [validate, test]
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.6.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
